<?php

namespace App\Http\Resources\Api;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class ProductResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return[

            'productID' => $this->productID,
'type' => $this->type,
'active' => $this->active,
'status' => $this->status,
'name' => $this->name,
'code' => $this->code,
'code2' => $this->code2,
'code3' => $this->code3,
'supplierCode' => $this->supplierCode,
'code5' => $this->code5,
'code6' => $this->code6,
'code7' => $this->code7,
'code8' => $this->code8,
'groupID' => $this->groupID,
'groupName' => $this->groupName,
'price' => $this->price,
'displayedInWebshop' => $this->displayedInWebshop,
'categoryID' => $this->categoryID,
'categoryName' => $this->categoryName,
'supplierID' => $this->supplierID,
'supplierName' => $this->supplierName,
'unitID' => $this->unitID,
'unitName' => $this->unitName,
'taxFree' => $this->taxFree,
'deliveryTime' => $this->deliveryTime,
'vatrateID' => $this->vatrateID,
'vatrate' => $this->vatrate,
'hasQuickSelectButton' => $this->hasQuickSelectButton,
'isGiftCard' => $this->isGiftCard,
'isRegularGiftCard' => $this->isRegularGiftCard,
'nonDiscountable' => $this->nonDiscountable,
'nonRefundable' => $this->nonRefundable,
'manufacturerName' => $this->manufacturerName,
'priorityGroupID' => $this->priorityGroupID,
'countryOfOriginID' => $this->countryOfOriginID,
'brandID' => $this->brandID,
'brandName' => $this->brandName,
'width' => $this->width,
'height' => $this->height,
'length' => $this->length,
'lengthInMinutes' => $this->lengthInMinutes,
'setupTimeInMinutes' => $this->setupTimeInMinutes,
'cleanupTimeInMinutes' => $this->cleanupTimeInMinutes,
'walkInService' => $this->walkInService,
'rewardPointsNotAllowed' => $this->rewardPointsNotAllowed,
'nonStockProduct' => $this->nonStockProduct,
'hasSerialNumbers' => $this->hasSerialNumbers,
'soldInPackages' => $this->soldInPackages,
'cashierMustEnterPrice' => $this->cashierMustEnterPrice,
'netWeight' => $this->netWeight,
'grossWeight' => $this->grossWeight,
'volume' => $this->volume,
'description' => $this->description,
'longdesc' => $this->longdesc,
'descriptionENG' => $this->descriptionENG,
'longdescENG' => $this->longdescENG,
'descriptionRUS' => $this->descriptionRUS,
'longdescRUS' => $this->longdescRUS,
'descriptionFIN' => $this->descriptionFIN,
'longdescFIN' => $this->longdescFIN,
'cost' => $this->cost,
'FIFOCost' => $this->FIFOCost,
'purchasePrice' => $this->purchasePrice,
'backbarCharges' => $this->backbarCharges,
'added' => $this->added,
'addedByUsername' => $this->addedByUsername,
'lastModified' => $this->lastModified,
'lastModifiedByUsername' => $this->lastModifiedByUsername,
'images' => $this->images,
'warehouses' => $this->warehouses,
'variationDescription' => $this->variationDescription,
'productVariations' => $this->productVariations,
'variationList' => $this->variationList,
'parentProductID' => $this->parentProductID,
'containerID' => $this->containerID,
'containerName' => $this->containerName,
'containerCode' => $this->containerCode,
'containerAmount' => $this->containerAmount,
'packagingType' => $this->packagingType,
'packages' => $this->packages,
'productPackages' => $this->productPackages,
'replacementProducts' => $this->replacementProducts,
'relatedProducts' => $this->relatedProducts,
'relatedFiles' => $this->relatedFiles,
'productComponents' => $this->productComponents,
'priceListPrice' => $this->priceListPrice,
'priceListPriceWithVat' => $this->priceListPriceWithVat,
'priceCalculationSteps' => $this->priceCalculationSteps,
'locationInWarehouse' => $this->locationInWarehouse,
'locationInWarehouseID' => $this->locationInWarehouseID,
'locationInWarehouseName' => $this->locationInWarehouseName,
'locationInWarehouseText' => $this->locationInWarehouseText,
'reorderMultiple' => $this->reorderMultiple,
'extraField1Title' => $this->extraField1Title,
'extraField1ID' => $this->extraField1ID,
'extraField1Code' => $this->extraField1Code,
'extraField1Name' => $this->extraField1Name,
'extraField2Title' => $this->extraField2Title,
'extraField2ID' => $this->extraField2ID,
'extraField2Code' => $this->extraField2Code,
'extraField2Name' => $this->extraField2Name,
'extraField3Title' => $this->extraField3Title,
'extraField3ID' => $this->extraField3ID,
'extraField3Code' => $this->extraField3Code,
'extraField3Name' => $this->extraField3Name,
'extraField4Title' => $this->extraField4Title,
'extraField4ID' => $this->extraField4ID,
'extraField4Code' => $this->extraField4Code,
'extraField4Name' => $this->extraField4Name,
'salesPackageClearBrownGlass' => $this->salesPackageClearBrownGlass,
'salesPackageGreenOtherGlass' => $this->salesPackageGreenOtherGlass,
'salesPackagePlasticPpPe' => $this->salesPackagePlasticPpPe,
'salesPackagePlasticPet' => $this->salesPackagePlasticPet,
'salesPackageMetalFe' => $this->salesPackageMetalFe,
'salesPackageMetalAl' => $this->salesPackageMetalAl,
'salesPackageOtherMetal' => $this->salesPackageOtherMetal,
'salesPackageCardboard' => $this->salesPackageCardboard,
'salesPackageWood' => $this->salesPackageWood,
'groupPackagePaper' => $this->groupPackagePaper,
'groupPackagePlastic' => $this->groupPackagePlastic,
'groupPackageMetal' => $this->groupPackageMetal,
'groupPackageWood' => $this->groupPackageWood,
'transportPackageWood' => $this->transportPackageWood,
'transportPackagePlastic' => $this->transportPackagePlastic,
'transportPackageCardboard' => $this->transportPackageCardboard,
'registryNumber' => $this->registryNumber,
'alcoholPercentage' => $this->alcoholPercentage,
'batches' => $this->batches,
'exciseDeclaration' => $this->exciseDeclaration,
'exciseFermentedProductUnder6' => $this->exciseFermentedProductUnder6,
'exciseWineOver6' => $this->exciseWineOver6,
'exciseFermentedProductOver6' => $this->exciseFermentedProductOver6,
'exciseIntermediateProduct' => $this->exciseIntermediateProduct,
'exciseOtherAlcohol' => $this->exciseOtherAlcohol,
'excisePackaging' => $this->excisePackaging,
'attributes' => $this->attributes,
'longAttributes' => $this->longAttributes,
'parameters' => $this->parameters,
'productReplacementHistory' => $this->productReplacementHistory,
        ];
    }
}
