<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('newsystem_product_matrix', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('productID');   //109
            $table->string('type');
            $table->tinyInteger('active')->nullable();
            $table->string('status')->nullable();
            $table->string('name')->nullable();
            $table->string('code')->nullable();
            $table->string('code2')->nullable();
            $table->string('code3')->nullable();
            $table->string('supplierCode')->length(255)->nullable();
            $table->string('code5')->nullable();
            $table->string('code6')->nullable();
            $table->string('code7')->nullable();
            $table->string('code8')->nullable();
            $table->integer('groupID')->nullable();
            $table->string('groupName')->nullable();
            $table->decimal('price')->nullable();
            $table->decimal('priceWithVat',)->nullable();
            $table->tinyInteger('displayedInWebshop')->nullable();
            $table->bigInteger('categoryID')->nullable();
            $table->string('categoryName')->nullable();
            $table->bigInteger('supplierID')->nullable();
            $table->string('supplierName')->nullable();
            $table->integer('unitID')->nullable();
            $table->string('unitName')->nullable();
            $table->tinyInteger('taxFree')->nullable();
            $table->string('deliveryTime')->nullable();
            $table->integer('vatrateID')->nullable();
            $table->decimal('vatrate')->nullable();
            $table->tinyInteger('hasQuickSelectButton')->nullable();
            $table->tinyInteger('isGiftCard')->nullable();
            $table->tinyInteger('isRegularGiftCard')->nullable();
            $table->tinyInteger('nonDiscountable')->nullable();
            $table->tinyInteger('nonRefundable')->nullable();
            $table->string('manufacturerName')->nullable();
            $table->integer('priorityGroupID')->nullable();
            $table->integer('countryOfOriginID')->nullable();
            $table->integer('brandID')->nullable();
            $table->string('brandName')->nullable();
            $table->integer('width')->nullable();
            $table->integer('height')->nullable();
            $table->integer('length')->nullable();
            $table->integer('lengthInMinutes')->nullable();
            $table->integer('setupTimeInMinutes')->nullable();
            $table->integer('cleanupTimeInMinutes')->nullable();
            $table->tinyInteger('walkInService')->nullable();
            $table->tinyInteger('rewardPointsNotAllowed')->nullable();
            $table->tinyInteger('nonStockProduct')->nullable();
            $table->tinyInteger('hasSerialNumbers')->nullable();
            $table->tinyInteger('soldInPackages')->nullable();
            $table->tinyInteger('cashierMustEnterPrice')->nullable();
            $table->float('netWeight')->nullable();
            $table->float('grossWeight')->nullable();
            $table->integer('volume')->nullable();
            $table->text('description')->nullable();
            $table->text('longdesc')->nullable();
            $table->text('descriptionENG')->nullable();
            $table->text('longdescENG')->nullable();
            $table->text('descriptionRUS')->nullable();
            $table->text('longdescRUS')->nullable();
            $table->text('descriptionFIN')->nullable();
            $table->text('longdescFIN')->nullable();
            $table->decimal('cost')->nullable();
            $table->decimal('FIFOCost')->nullable();
            $table->decimal('purchasePrice')->nullable();
            $table->decimal('backbarCharges')->nullable();
            $table->dateTime('added')->nullable();
            $table->string('addedByUsername')->length(16)->nullable();
            $table->dateTime('lastModified')->nullable();
            $table->string('lastModifiedByUsername')->length(16)->nullable();
            $table->text('images')->nullable();
            $table->text('warehouses')->nullable();
            $table->text('variationDescription')->nullable();
            $table->text('productVariations')->nullable();
            $table->text('variationList')->nullable();
            $table->bigInteger('parentProductID')->nullable();
            $table->integer('containerID')->nullable();
            $table->string('containerName')->length(255)->nullable();
            $table->string('containerCode')->length(255)->nullable();
            $table->string('containerAmount')->nullable();
            $table->string('packagingType')->nullable();
            $table->text('packages')->nullable();
            $table->text('productPackages')->nullable();
            $table->text('replacementProducts')->nullable();
            $table->text('relatedProducts')->nullable();
            $table->text('relatedFiles')->nullable();
            $table->text('productComponents')->nullable();
            $table->decimal('priceListPrice')->nullable();
            $table->decimal('priceListPriceWithVat')->nullable();
            $table->text('priceCalculationSteps')->default(0);
            $table->string('locationInWarehouse')->nullable();
            $table->integer('locationInWarehouseID')->nullable();
            $table->string('locationInWarehouseName')->nullable();
            $table->string('locationInWarehouseText')->nullable();
            $table->integer('reorderMultiple')->nullable();
            $table->string('extraField1Title')->length(255)->nullable();
            $table->integer('extraField1ID')->nullable();
            $table->string('extraField1Code')->length(50)->nullable();
            $table->string('extraField1Name')->length(255)->nullable();
            $table->string('extraField2Title')->length(255)->nullable();
            $table->integer('extraField2ID')->nullable();
            $table->string('extraField2Code')->length(50)->nullable();
            $table->string('extraField2Name')->length(255)->nullable();
            $table->string('extraField3Title')->length(255)->nullable();
            $table->integer('extraField3ID')->nullable();
            $table->string('extraField3Code')->length(50)->nullable();
            $table->string('extraField3Name')->length(255)->nullable();
            $table->string('extraField4Title')->length(255)->nullable();
            $table->integer('extraField4ID')->nullable();
            $table->string('extraField4Code')->length(50)->nullable();
            $table->string('extraField4Name')->length(255)->nullable();
            // To retrieve the following fields, set input parameter getPackagingMaterials = "1". These fields are not included in the output by default.
            $table->double('salesPackageClearBrownGlass')->nullable();
            $table->double('salesPackageGreenOtherGlass')->nullable();
            $table->double('salesPackagePlasticPpPe')->nullable();
            $table->double('salesPackagePlasticPet')->nullable();
            $table->double('salesPackageMetalFe')->nullable();
            $table->double('salesPackageMetalAl')->nullable();
            $table->double('salesPackageOtherMetal')->nullable();
            $table->double('salesPackageCardboard')->nullable();
            $table->double('salesPackageWood')->nullable();
            $table->double('groupPackagePaper')->nullable();
            $table->double('groupPackagePlastic')->nullable();
            $table->double('groupPackageMetal')->nullable();
            $table->double('groupPackageWood')->nullable();
            $table->double('transportPackageWood')->nullable();
            $table->double('transportPackagePlastic')->nullable();
            $table->double('transportPackageCardboard')->nullable();
            // Alcohol details.
            $table->string('registryNumber')->nullable();
            $table->double('alcoholPercentage')->nullable();
            $table->string('batches')->nullable();
            $table->string('exciseDeclaration')->nullable();
            $table->double('exciseFermentedProductUnder6')->nullable();
            $table->double('exciseWineOver6')->nullable();
            $table->double('exciseFermentedProductOver6')->nullable();
            $table->double('exciseIntermediateProduct')->nullable();
            $table->double('exciseOtherAlcohol')->nullable();
            $table->double('excisePackaging')->nullable();
            //****
            $table->text('attributes')->nullable();
            $table->text('longAttributes')->nullable();
            $table->text('parameters')->nullable();
            $table->text('productReplacementHistory')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
